In [2]:
# MATRICES

from scipy import linalg
import numpy as np

In [3]:
a = np.array([ [1,0,3],[0,1,-2],[1,1,2] ])
a

array([[ 1,  0,  3],
       [ 0,  1, -2],
       [ 1,  1,  2]])

In [4]:
linalg.det(a) # Calcular determinante

0.9999999999999998

In [5]:
linalg.inv(a) # Inversa de la matriz

array([[ 4.,  3., -3.],
       [-2., -1.,  2.],
       [-1., -1.,  1.]])

In [6]:
"""
7x + 2y = 8
4x + 5y = 10
"""

matA = [ [7,2], [4,5] ]
matA

[[7, 2], [4, 5]]

In [8]:
matB = [[8],[10]]
matB

[[8], [10]]

In [12]:
linalg.solve(matA,matB)

array([[0.74074074],
       [1.40740741]])

In [14]:
matC = np.array( [[2,4,6],[2,-3,-4],[3,4,5]] )
matD = np.array([[-12],[15],[-8]])
linalg.solve(matC,matD)

array([[ 2.],
       [-1.],
       [-2.]])

In [15]:
(x,y,z) = linalg.solve(matC,matD)

In [16]:
x

array([2.])

In [17]:
y

array([-1.])

In [18]:
z

array([-2.])

In [20]:
"""
Resolver el siguiente sistema de ecuaciones, validar que tenga solución usando el determinante:

5x1 + 4x2 -1x + 2x4 -9x5 = 29
4x1 + 3x2 -5x3 -5x4 + 4x5 = -65
6x1 - 6x2 -3x3 -9x4 +4x5 = -113
-8x1 + 8x2 +5x3 -3x4 -6x5 = 35
-3x1 - 7x2 +2x3 -5x4 +4x5 = -50

"""

matrizP = np.array([ [5,4,-1,2,-9],[4,3,-5,-5,4],[6,-6,-3,-9,4],[-8,8,5,-3,-6],[-3,-7,2,-5,4] ])
matrizQ = np.array([ [29],[-65],[-113],[35],[-50] ])

linalg.det(matrizP) #Determinante no debe ser 0 para tener solución

-8519.999999999993

In [21]:
(x1,x2,x3,x4,x5) = linalg.solve(matrizP,matrizQ)

In [22]:
x1

array([-2.])

In [23]:
x2

array([2.])

In [24]:
x3

array([3.])

In [25]:
x4

array([8.])

In [26]:
x5

array([-2.])