In [1]:
import pandas as pd
import numpy as np


grades = pd.read_csv('grades.csv')

grades

exam  student_id  grade
0      1           1   86.0
1      1           2   65.0
2      1           3   70.0
3      1           4   98.0
4      1           5   89.0
5      1           6    NaN
6      1           7   75.0
7      1           8   56.0
8      1           9   90.0
9      1          10   81.0
10     2           1   79.0
11     2           2   60.0
12     2           3   78.0
13     2           4   75.0
14     2           5    NaN
15     2           6   80.0
16     2           7   87.0
17     2           8   82.0
18     2           9   95.0
19     2          10   96.0
20     3           1   78.0
21     3           2   80.0
22     3           3   87.0
23     3           4    NaN
24     3           5   89.0
25     3           6   90.0
26     3           7  100.0
27     3           8   72.0
28     3           9   73.0
29     3          10   75.0
30     4           1    NaN
31     4           2   80.0
32     4           3   81.0
33     4           4   82.0
34     4           5   83.0
35     4           6   84.0
36     4           7   85.0
37     4           8   86.0
38     4           9   87.0
39     4          10   88.0
40     5           1   90.0
41     5           2    NaN
42     5           3   91.0
43     5           4   92.0
44     5           5   93.0
45     5           6   94.0
46     5           7   95.0
47     5           8   96.0
48     5           9   97.0
49     5          10   98.0

In [2]:
grades.head(10)

exam  student_id  grade
0     1           1   86.0
1     1           2   65.0
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [3]:
grades.iloc[:10]

exam  student_id  grade
0     1           1   86.0
1     1           2   65.0
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [4]:
grades.iloc[2:10]

exam  student_id  grade
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [6]:
grades['grade'] = grades['grade'].fillna(0)
grades

exam  student_id  grade
0      1           1   86.0
1      1           2   65.0
2      1           3   70.0
3      1           4   98.0
4      1           5   89.0
5      1           6    0.0
6      1           7   75.0
7      1           8   56.0
8      1           9   90.0
9      1          10   81.0
10     2           1   79.0
11     2           2   60.0
12     2           3   78.0
13     2           4   75.0
14     2           5    0.0
15     2           6   80.0
16     2           7   87.0
17     2           8   82.0
18     2           9   95.0
19     2          10   96.0
20     3           1   78.0
21     3           2   80.0
22     3           3   87.0
23     3           4    0.0
24     3           5   89.0
25     3           6   90.0
26     3           7  100.0
27     3           8   72.0
28     3           9   73.0
29     3          10   75.0
30     4           1    0.0
31     4           2   80.0
32     4           3   81.0
33     4           4   82.0
34     4           5   83.0
35     4           6   84.0
36     4           7   85.0
37     4           8   86.0
38     4           9   87.0
39     4          10   88.0
40     5           1   90.0
41     5           2    0.0
42     5           3   91.0
43     5           4   92.0
44     5           5   93.0
45     5           6   94.0
46     5           7   95.0
47     5           8   96.0
48     5           9   97.0
49     5          10   98.0

In [14]:
#exam1 = grades.loc[grades['exam'] == 1]
#exam1

exam1_mean = grades.loc[grades['exam'] == 1]['grade'].mean()
exam1_mean


71.0

In [15]:
grades.loc[grades['grade'] >= 70 ]['grade'].values

array([ 86.,  70.,  98.,  89.,  75.,  90.,  81.,  79.,  78.,  75.,  80.,
        87.,  82.,  95.,  96.,  78.,  80.,  87.,  89.,  90., 100.,  72.,
        73.,  75.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.])

In [16]:
grades.loc[grades['grade'] < 70 ]['grade'].values

array([65.,  0., 56., 60.,  0.,  0.,  0.,  0.])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
list1 = [1,2,3,4,5]
list1

array1 = np.array(list1)
array1

array([1, 2, 3, 4, 5])

In [23]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
list2

array2 = np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones((7,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
np.linspace(1,2,9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [27]:
np.linspace(0,1,22) # 22 números entre 0 y 1

array([0.        , 0.04761905, 0.0952381 , 0.14285714, 0.19047619,
       0.23809524, 0.28571429, 0.33333333, 0.38095238, 0.42857143,
       0.47619048, 0.52380952, 0.57142857, 0.61904762, 0.66666667,
       0.71428571, 0.76190476, 0.80952381, 0.85714286, 0.9047619 ,
       0.95238095, 1.        ])

In [28]:
np.random.randint(1,20,5) # 5 números enteros entre 1 y 20

array([ 9,  9,  8, 15, 13])

In [29]:
array_random = np.random.randint(1,20,10)
array_random

array([ 3,  8,  3,  1,  2,  4,  3,  2, 10, 14])

In [30]:
array_random.min()

1

In [31]:
array_random.max()

14

In [32]:
array_random.argmin() #posición mínimo

3

In [33]:
array_random.argmax() #posición máximo

9

In [34]:
array_random.shape #tamaño o longitud

(10,)

In [35]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
array2[1][1]

5