In [2]:
import pandas as pd
import numpy as np

In [3]:
grades=pd.read_csv('grades.csv')

In [3]:
grades


exam  student_id  grade
0      1           1   86.0
1      1           2   65.0
2      1           3   70.0
3      1           4   98.0
4      1           5   89.0
5      1           6    NaN
6      1           7   75.0
7      1           8   56.0
8      1           9   90.0
9      1          10   81.0
10     2           1   79.0
11     2           2   60.0
12     2           3   78.0
13     2           4   75.0
14     2           5    NaN
15     2           6   80.0
16     2           7   87.0
17     2           8   82.0
18     2           9   95.0
19     2          10   96.0
20     3           1   78.0
21     3           2   80.0
22     3           3   87.0
23     3           4    NaN
24     3           5   89.0
25     3           6   90.0
26     3           7  100.0
27     3           8   72.0
28     3           9   73.0
29     3          10   75.0
30     4           1    NaN
31     4           2   80.0
32     4           3   81.0
33     4           4   82.0
34     4           5   83.0
35     4           6   84.0
36     4           7   85.0
37     4           8   86.0
38     4           9   87.0
39     4          10   88.0
40     5           1   90.0
41     5           2    NaN
42     5           3   91.0
43     5           4   92.0
44     5           5   93.0
45     5           6   94.0
46     5           7   95.0
47     5           8   96.0
48     5           9   97.0
49     5          10   98.0

In [4]:
grades.head(10)

exam  student_id  grade
0     1           1   86.0
1     1           2   65.0
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [5]:
grades.iloc[:10]

exam  student_id  grade
0     1           1   86.0
1     1           2   65.0
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [6]:
grades.iloc[2:10]

exam  student_id  grade
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [7]:
grades.iloc[20:30]

exam  student_id  grade
20     3           1   78.0
21     3           2   80.0
22     3           3   87.0
23     3           4    NaN
24     3           5   89.0
25     3           6   90.0
26     3           7  100.0
27     3           8   72.0
28     3           9   73.0
29     3          10   75.0

In [8]:
grades['grade'].fillna(0)

0      86.0
1      65.0
2      70.0
3      98.0
4      89.0
5       0.0
6      75.0
7      56.0
8      90.0
9      81.0
10     79.0
11     60.0
12     78.0
13     75.0
14      0.0
15     80.0
16     87.0
17     82.0
18     95.0
19     96.0
20     78.0
21     80.0
22     87.0
23      0.0
24     89.0
25     90.0
26    100.0
27     72.0
28     73.0
29     75.0
30      0.0
31     80.0
32     81.0
33     82.0
34     83.0
35     84.0
36     85.0
37     86.0
38     87.0
39     88.0
40     90.0
41      0.0
42     91.0
43     92.0
44     93.0
45     94.0
46     95.0
47     96.0
48     97.0
49     98.0
Name: grade, dtype: float64

In [9]:
grades.iloc[:10]

exam  student_id  grade
0     1           1   86.0
1     1           2   65.0
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [10]:
grades.loc[grades['exam']==1]

exam  student_id  grade
0     1           1   86.0
1     1           2   65.0
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [11]:
grades.loc[grades['exam']==1]['grade'].mean()

78.88888888888889

In [56]:
grades.loc?


ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
exam1_mean=grades.loc[grades['exam']==1]['grade'].mean()
exam1_mean

In [ ]:
grades.loc[grades['grade'] >= 70]['grade'].values

In [ ]:
grades.loc[grades['grade'] < 70]['grade'].values

In [ ]:
array0 = np.array([])

In [ ]:
array0

In [ ]:
list1=[1,2,3,4,5]
list1

In [ ]:
array1=np.array(list1)
array1

In [31]:
list2=[[1,2,3],[4,5,6],[7,8,9]]

In [32]:
list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [33]:
array2=np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(5)

In [ ]:
np.arange(0,11,2)

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((7,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.linspace(1,2,9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [18]:
np.linspace(0,1,22)

array([0.        , 0.04761905, 0.0952381 , 0.14285714, 0.19047619,
       0.23809524, 0.28571429, 0.33333333, 0.38095238, 0.42857143,
       0.47619048, 0.52380952, 0.57142857, 0.61904762, 0.66666667,
       0.71428571, 0.76190476, 0.80952381, 0.85714286, 0.9047619 ,
       0.95238095, 1.        ])

In [19]:
array_radom=np.random.randint(1,20,10)

In [20]:
array_radom

array([12, 18, 13,  5,  5, 11, 17, 15,  7,  4])

In [21]:
array_radom.min()

4

In [22]:
array_radom.max()

18

In [23]:
#La posición del mínimo
array_radom.argmin()

9

In [24]:
#La posición del máximo
array_radom.argmax()

1

In [25]:
array_radom.shape

(10,)

In [34]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
array2[1][1]

5

In [36]:
array2[0][0]


1

In [37]:
array2[2][2]


9

In [60]:
array2[1][2]

6

In [39]:
arrayA = np.arange(1,21,2)
arrayA

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [40]:
arrayB = np.arange(1,11)
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arrayA.shape

(10,)

In [42]:
arrayB.shape

(10,)

In [43]:
arrayA + arrayB

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [45]:
arrayA - arrayB

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arrayA * arrayB #Este no es un producto punto. Es la multiplicación de elemento por elemento

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190])

In [47]:
arrayC = np.array([ [1,2,3],[4,5,6] ])
arrayC

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arrayD = np.array( [[7,8,9],[10,11,12]] )
arrayD

array([[ 7,  8,  9],
       [10, 11, 12]])

In [49]:
arrayC + arrayD

array([[ 8, 10, 12],
       [14, 16, 18]])

In [50]:
arrayC * arrayD

array([[ 7, 16, 27],
       [40, 55, 72]])

In [52]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
2 * array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [54]:
array2 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
array2 - 1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])